# Generated by Django 4.2.5 on 2023-12-23 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(upload_to='')),
                ('ciudad', models.CharField(max_length=65)),
                ('provincia', models.CharField(max_length=65)),
                ('edad', models.IntegerField()),
                ('profesion', models.CharField(choices=[('limpieza', 'Limpiador/a'), ('reparacion', 'Reparador/a'), ('jardineria', 'Jardinero/a'), ('electricista', 'Electricista'), ('fontanero', 'Fontanero/a'), ('carpintero', 'Carpintero/a'), ('pintor', 'Pintor/a'), ('albanil', 'Albañil'), ('cerrajero', 'Cerrajero/a'), ('podador_arboles', 'Podador/a de árboles'), ('disenador_jardines', 'Diseñador/a de jardines'), ('conductor_mudanzas', 'Conductor/a de mudanzas'), ('ayudante_mudanzas', 'Ayudante de mudanzas'), ('mensajero', 'Mensajero/a'), ('repartidor_alimentos', 'Repartidor/a de alimentos'), ('repartidor_paquetes', 'Repartidor/a de paquetes'), ('ninera', 'Niñera'), ('cuidador_personas_mayores', 'Cuidador/a de personas mayores'), ('asistente_personal', 'Asistente/a personal'), ('montador_muebles', 'Montador/a de muebles'), ('desmontador_muebles', 'Desmontador/a de muebles'), ('reparador_computadoras', 'Reparador/a de computadoras'), ('tecnico_electronica', 'Técnico/a en electrónica'), ('instalador_seguridad', 'Instalador/a de sistemas de seguridad'), ('disenador_grafico', 'Diseñador/a gráfico/a'), ('ilustrador', 'Ilustrador/a'), ('fotografo', 'Fotógrafo/a'), ('entrenador_personal', 'Entrenador/a personal'), ('instructor_yoga', 'Instructor/a de yoga'), ('preparador_fisico', 'Preparador/a físico/a'), ('organizador_eventos', 'Organizador/a de eventos'), ('animador', 'Animador/a'), ('dj', 'DJ'), ('asistente_administrativo', 'Asistente/a administrativo/a'), ('secretario', 'Secretario/a'), ('data_entry', 'Data Entry')], max_length=100)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
