# Generated by Django 5.0 on 2023-12-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_usuario_apellido_usuario_email_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='first_login',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 11:11:11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='job',
            field=models.ManyToManyField(blank=True, null=True, related_name='usuarios_trabajo', to='backend_api.job'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
