# Generated by Django 5.0 on 2024-01-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_empleo_imagen_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_trabajo/')),
            ],
        ),
        migrations.RemoveField(
            model_name='empleo',
            name='imagen_trabajo',
        ),
        migrations.AddField(
            model_name='empleo',
            name='imagenes_trabajo',
            field=models.ManyToManyField(blank=True, to='backend_api.imagentrabajo'),
        ),
    ]
