# Generated by Django 5.0 on 2024-01-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_imagentrabajo_remove_empleo_imagen_trabajo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleo',
            name='imagenes_trabajo',
        ),
        migrations.AddField(
            model_name='empleo',
            name='imagen_trabajo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ImagenTrabajo',
        ),
    ]
