# Generated by Django 5.0 on 2024-01-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_remove_empleo_imagenes_trabajo_empleo_imagen_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='oferente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.oferente'),
        ),
    ]
