# Generated by Django 5.0 on 2024-01-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0011_alter_empleo_oferente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='trabajo',
            field=models.CharField(blank=True, choices=[('por hora de trabajo', 'por hora de trabajo'), ('por trabajo completo', 'por trabajo completo')], max_length=100, null=True),
        ),
    ]
