# Generated by Django 5.0 on 2024-01-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_alter_empleo_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleo',
            name='para_cuando',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
