# Generated by Django 5.0 on 2024-01-08 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0014_remove_empleo_para_cuando_alter_empleo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='empleo',
            name='trabajo',
            field=models.CharField(blank=True, choices=[('por hora de trabajo', 'por hora de trabajo'), ('por trabajo completo', 'por trabajo completo'), ('A convenir', 'A convenir')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('calificaciones', models.FloatField(blank=True, null=True)),
                ('habilidades', models.ManyToManyField(blank=True, related_name='trabajadores_habilidad', to='backend_api.job')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.empleo')),
                ('oferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.oferente')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.trabajador')),
            ],
        ),
    ]
