
# Generated by Django 5.0 on 2024-01-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0016_alter_postulacion_trabajador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='oferente',
        ),
    ]
