# Generated by Django 5.0 on 2024-01-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0017_remove_postulacion_oferente'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='contratado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='mensaje',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
